### ISSUE TITLE
33/5000  Vue-highlight-code plug-in is already installed, prompting you to install it again

### ISSUE THREAD

**Issue by didiplus** [F-one-1/vue-highlight-code#1]
The environment：3.2.19
![image](https://user-images.githubusercontent.com/20027156/172030967-e541685d-ad7a-40e1-9ac2-40fe81066f79.png)

**Comment by F-one-1** [comment]
please try again in v0.1.8 ，maybe is OK

**Comment by didiplus** [comment]
upgrade v0.1.8, There is a new problem, CSS cannot load.
![image](https://didiplus.oss-cn-hangzhou.aliyuncs.com/static/微信图片_20220607093937.png)

**Comment by F-one-1** [comment]
you may need to see the [demo live](https://stackblitz.com/edit/github-flf8ku?file=src%2FApp.vue), import the component and style, such as
```js
import { HighCode } from 'vue-highlight-code';
import 'vue-highlight-code/dist/style.css';
```

**Comment by didiplus** [comment]
I copied your demo into my project, but the CSS didn't load  ,The following 
![image](https://didiplus.oss-cn-hangzhou.aliyuncs.com/static/20220607100745.png)

**Comment by F-one-1** [comment]
I don't know why this solution but I created a [template demo](https://stackblitz.com/edit/vue-f7to5t?file=src/App.vue) to reproduce. You can reproduce your code problem in demo. and copy link to this issue.

**Comment by F-one-1** [comment]
I can't locate the problem, please provides more information, including developer tools, and version lock
