### ISSUE TITLE
可以支持一下滚动条或者根据代码长度自适应元素高度吗。

### ISSUE THREAD

**Issue by tommyme** [F-one-1/vue-highlight-code#2]
<img width="680" alt="image" src="https://user-images.githubusercontent.com/56789465/186298737-9e1a05e6-058f-48dc-8622-33deabb5dea6.png">
您的代码实现很优雅，如果有文档就更好了。
在代码比较多的时候代码块不能自适应高度，很头疼

**Comment by F-one-1** [comment]
这确实是个问题，我正在修理它，文档也在构建中  wait a moment

**Comment by F-one-1** [comment]
您可以先看一下这个 [在线demo](https://stackblitz.com/github/F-one-1/vue-highlight-code?file=src%2FApp.vue)，这样应该可以完成自适应高度

**Comment by tommyme** [comment]
thanks! It's so coooool.
