### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Xeyos88** [F-one-1/vue-highlight-code#3]
It doesn't work with typescript.

`Could not find a declaration file for module 'vue-highlight-code'. '/home/etopa/Development/components-dev/node_modules/vue-highlight-code/dist/vue-highlight-code.umd.js' implicitly has an 'any' type.
  Try npm i --save-dev @types/vue-highlight-code if it exists or add a new declaration (.d.ts) file containing declare module 'vue-highlight-code';`

**Comment by F-one-1** [comment]
Yeah, the Typescript support that the component should have, wait a moment in a new release
